In [88]:
import pandas as pd
import numpy as np
from typing import List
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.preprocessing import OneHotEncoder

In [2]:
data=pd.read_csv('../data/interim/user_track_df.csv')

In [93]:
df = data.copy()
df.drop(df.columns[0], axis=1, inplace=True)
df.drop([col for col, val in df.sum().iteritems() if val < 5], axis=1, inplace=True)
df.index.name="user_id"

In [4]:
songs= list(df)
songs_id = pd.DataFrame(songs)
songs_id.rename( columns={0:'song_name'}, inplace=True )
songs_id.index.name='song_id'
songsdict = dict(zip(songs,range(len(songs))))

In [94]:
dft=df.T
dft.reset_index(inplace=True,drop=True)
dft.index.name="song_id"

user_id,0,1,2,3,4,5,6,7,8,9,...,580,581,582,583,584,585,586,587,588,589
song_id,,,,,,,,,,,,,,,,,,,,,
!!!_A New Name,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
!!!_All My Heroes Are Weirdos,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
!!!_Bend Over Beethoven,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
!!!_Heart Of Hearts,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
!!!_Must Be The Moon,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [101]:
dft.head()

user_id,0,1,2,3,4,5,6,7,8,9,...,580,581,582,583,584,585,586,587,588,589
song_id,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [118]:
listen_count=dft.values

In [125]:
bins = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 2214]

In [132]:
df_song_reduced= pd.cut(dft.values.flatten(), bins=bins, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [134]:
listen_counts = pd.DataFrame(df_song_reduced.groupby.values.size(), columns=['count']).reset_index(drop=False)

AttributeError: 'Categorical' object has no attribute 'groupby'